/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javamsgque_MqBufferS */

#ifndef _Included_javamsgque_MqBufferS
#define _Included_javamsgque_MqBufferS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javamsgque_MqBufferS
 * Method:    Delete
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javamsgque_MqBufferS_Delete
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    Dup
 * Signature: ()Ljavamsgque/MqBufferS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqBufferS_Dup
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetType
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_javamsgque_MqBufferS_GetType
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetY
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_javamsgque_MqBufferS_GetY
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetO
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javamsgque_MqBufferS_GetO
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetS
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_javamsgque_MqBufferS_GetS
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javamsgque_MqBufferS_GetI
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetF
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_javamsgque_MqBufferS_GetF
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetW
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javamsgque_MqBufferS_GetW
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetD
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_javamsgque_MqBufferS_GetD
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetB
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_javamsgque_MqBufferS_GetB
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqBufferS
 * Method:    GetC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javamsgque_MqBufferS_GetC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
