/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javamsgque_MqS_WAIT */

#ifndef _Included_javamsgque_MqS_WAIT
#define _Included_javamsgque_MqS_WAIT
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
