/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javamsgque_MqDumpS */

#ifndef _Included_javamsgque_MqDumpS
#define _Included_javamsgque_MqDumpS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javamsgque_MqDumpS
 * Method:    DumpFree
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javamsgque_MqDumpS_DumpFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
