DX_DIST = \
.CreateListMk.bash \
.PERSONAL \
Doxyfile.generic \
Makefile.am \
ccmsgque_private/Doxyfile \
ccmsgque_private/main.doc \
ccmsgque_public/Doxyfile \
csmsgque_public/Doxyfile \
footer.html \
javamsgque_private/Doxyfile \
javamsgque_private/main.doc \
javamsgque_public/Doxyfile \
libmsgque_private/Doxyfile \
libmsgque_private/main.doc \
libmsgque_public/Doxyfile \
list.mk \
main/Doxyfile \
main/context.doc \
main/faq.doc \
main/features.doc \
main/filter.doc \
main/main.doc \
main/pages.doc \
main/performance.doc \
main/work_package_2.doc \
man/Doxyfile.ccmsgque \
man/Doxyfile.csmsgque \
man/Doxyfile.gomsgque \
man/Doxyfile.javamsgque \
man/Doxyfile.libmsgque \
man/template.msgque \
man/Doxyfile.msgqueforphp \
man/Doxyfile.perlmsgque \
man/Doxyfile.pymsgque \
man/Doxyfile.rubymsgque \
man/Doxyfile.tclmsgque \
man/Doxyfile.vbmsgque \
man/customdoxygen.css \
man/genmsgque.doc \
man/local.generic \
man/tutorial.doc \
msgqueforphp_private/Doxyfile \
msgqueforphp_private/main.doc \
pymsgque_private/Doxyfile \
pymsgque_private/main.doc \
rubymsgque_private/Doxyfile \
rubymsgque_private/main.doc \
stylesheet.css \
tclmsgque_private/Doxyfile \
tclmsgque_private/main.doc
