#!/bin/bash
#+
#:  \file       sbin/log
#:  \brief      \$Id$
#:  
#:  (C) 2011 - NHI - #1 - Project - Group
#:  
#:  \version    \$Rev$
#:  \author     EMail: aotto1968 at users.berlios.de
#:  \attention  this software has GPL permissions to copy
#:              please contact AUTHORS for additional information
#:


# call shell-command and put the output into a file


CMD="$@"

LOG=$1; shift
case $LOG in
  make|tclsh|java|mono|python|perl)	
    for X ; do
      [[ $X == -* ]] && continue
      LOG=$X
      break
    done
  ;;
esac

LOG=$(basename "$LOG")

$CMD 2>&1 | tee $LOG.log

echo -e "\n\n -> created: $LOG.log"

