/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javamsgque_MqS_START */

#ifndef _Included_javamsgque_MqS_START
#define _Included_javamsgque_MqS_START
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
