/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javamsgque_MqFactoryS */

#ifndef _Included_javamsgque_MqFactoryS
#define _Included_javamsgque_MqFactoryS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javamsgque_MqFactoryS
 * Method:    Add
 * Signature: (Ljava/lang/String;Ljava/lang/Class;)Ljavamsgque/MqFactoryS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqFactoryS_Add
  (JNIEnv *, jclass, jstring, jclass);

/*
 * Class:     javamsgque_MqFactoryS
 * Method:    Default
 * Signature: (Ljava/lang/String;Ljava/lang/Class;)Ljavamsgque/MqFactoryS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqFactoryS_Default
  (JNIEnv *, jclass, jstring, jclass);

/*
 * Class:     javamsgque_MqFactoryS
 * Method:    DefaultIdent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javamsgque_MqFactoryS_DefaultIdent
  (JNIEnv *, jclass);

/*
 * Class:     javamsgque_MqFactoryS
 * Method:    Get
 * Signature: (Ljava/lang/String;)Ljavamsgque/MqFactoryS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqFactoryS_Get__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     javamsgque_MqFactoryS
 * Method:    Get
 * Signature: ()Ljavamsgque/MqFactoryS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqFactoryS_Get__
  (JNIEnv *, jclass);

/*
 * Class:     javamsgque_MqFactoryS
 * Method:    GetCalled
 * Signature: (Ljava/lang/String;)Ljavamsgque/MqFactoryS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqFactoryS_GetCalled
  (JNIEnv *, jclass, jstring);

/*
 * Class:     javamsgque_MqFactoryS
 * Method:    New
 * Signature: ()Ljavamsgque/MqS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqFactoryS_New
  (JNIEnv *, jobject);

/*
 * Class:     javamsgque_MqFactoryS
 * Method:    Copy
 * Signature: (Ljava/lang/String;)Ljavamsgque/MqFactoryS;
 */
JNIEXPORT jobject JNICALL Java_javamsgque_MqFactoryS_Copy
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
