DX_DIST = \
.CreateListMk.bash \
.PERSONAL \
Doxyfile.generic \
Makefile.am \
ccmsgque_public/Doxyfile \
ccmsgque_public/main.doc \
csmsgque_public/Doxyfile \
csmsgque_public/main.doc \
footer.html \
javamsgque_private/Doxyfile \
javamsgque_private/main.doc \
javamsgque_public/Doxyfile \
javamsgque_public/main.doc \
libmsgque_private/Doxyfile \
libmsgque_private/main.doc \
libmsgque_public/Doxyfile \
libmsgque_public/main.doc \
list.mk \
main/Doxyfile \
main/client_versa_server.doc \
main/context.doc \
main/factory.doc \
main/faq.doc \
main/features.doc \
main/main.doc \
main/master_versa_slave.doc \
main/pages.doc \
main/parent_versa_child.doc \
main/performance.doc \
main/service_call.doc \
main/shell.doc \
main/thread.doc \
man/Doxyfile.ccmsgque \
man/Doxyfile.csmsgque \
man/Doxyfile.javamsgque \
man/Doxyfile.libmsgque \
man/Doxyfile.pymsgque \
man/Doxyfile.tclmsgque \
man/customdoxygen.css \
man/genmsgque.doc \
man/local.generic \
pymsgque_private/Doxyfile \
pymsgque_private/main.doc \
tclmsgque_private/Doxyfile \
tclmsgque_private/main.doc \
doxygen.sh
